---
- name: Install Browsers with Flatpak
  hosts: localhost
  become: True
  become_user: root
  tasks:
    - name: add backports repo
      apt_repository:
        repo: deb http://deb.debian.org/debian stretch-backports main contrib non-free
        state: present

    - name: install flatpak
      apt:
        default_release: stretch-backports
        name: flatpak
        state: latest
        update_cache: yes

    - name: add unofficial firefox remote
      command: flatpak remote-add --if-not-exists --from org.mozilla.FirefoxRepo \
        https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo

    - name: install Firefox Developer Edition
      command: flatpak install -y org.mozilla.FirefoxRepo org.mozilla.FirefoxDevEdition
      args:
        creates: /var/lib/flatpak/app/org.mozilla.FirefoxDevEdition

    - name: update flatpak applications
      command: flatpak update

    - name: install chromium and update
      package:
        name: chromium
        state: present
        update_cache: yes
