---
- name: Setup Flatpak and Install Apps
  hosts: localhost
  become: True
  become_user: root
  tasks:
    - name: add backports repo
      apt_repository:
        repo: deb http://deb.debian.org/debian stretch-backports main contrib non-free
        state: present

    - name: install flatpak
      apt:
        default_release: stretch-backports
        name: flatpak
        state: latest
        update_cache: yes

    - name: add flathub remote
      flatpak_remote:
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
        name: flathub

    - name: install Flatpak Apps
      flatpak:
        method: user
        name: "{{ item }}"
      loop:
        - com.discordapp.Discord
        - com.getpostman.Postman
        - com.jetbrains.IntelliJ-IDEA-Ultimate
        - com.slack.Slack
        - com.visualstudio.code
        - org.filezillaproject.Filezilla
        - org.gimp.GIMP
        - org.libreoffice.LibreOffice

    - name: update flatpak applications
      command: flatpak update -y
