---
- name: Set Up Lisp
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: install lisp packages
      become: True
      become_user: root
      package: name="{{ packages }}"
      vars:
        packages:
          - cl-quicklisp
          - sbcl
          - clisp
