---
- name: Setup Flatpak and Install Apps
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: install flatpak
      become: True
      become_user: root
      package:
        name: flatpak
        state: latest
        update_cache: yes

    - name: add flathub remote
      flatpak_remote:
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
        name: flathub

    - name: add unofficial firefox remote
      flatpak_remote:
        flatpakrepo_url: https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo
        method: user
        name: FirefoxRepo

    - name: install Flatpak Apps from flathub
      flatpak:
        method: user
        name: "{{ item }}"
        remote: flathub
      loop:
        - com.discordapp.Discord
        - com.getpostman.Postman
        - com.google.AndroidStudio
        - com.jetbrains.IntelliJ-IDEA-Ultimate
        - com.jetbrains.WebStorm
        - com.skype.Client
        - com.slack.Slack
        - com.visualstudio.code
        - org.audacityteam.Audacity
        - org.filezillaproject.Filezilla
        - org.gimp.GIMP
        - org.libreoffice.LibreOffice
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC

    - name: install Firefox Dev Edition
      flatpak:
        method: user
        name: org.mozilla.FirefoxDevEdition
        remote: FirefoxRepo

    - name: update flatpak applications
      command: flatpak update --user -y

