---
- name: Set Up Node
  hosts: localhost
  become_user: "{{ username }}"
  tasks:
    - name: install system node
      become: True
      become_user: root
      package: name=nodejs
               state=present

    - name: ensure the ~/src-hub directory is present
      file: path=/home/{{ username }}/src-hub
            state=directory

    - name: clone nvm
      git: repo=https://github.com/creationix/nvm.git
           dest=/home/{{ username }}/src-hub/nvm
           update=no

    - name: create symlink to nvm
      file: path=/home/{{ username }}/.nvm
            src=/home/{{ username }}/src-hub/nvm
            state=link

    - name: set NVM_DIR in .zshrc
      lineinfile: dest=/home/{{ username}}/.oh-my-zsh/custom/nvm.zsh
                  regexp='export NVM_DIR'
                  line='export NVM_DIR="/home/{{ username }}/src-hub/nvm"'

    - name: source nvm in .zshrc
      lineinfile: dest=/home/{{ username }}/.zshrc
                  regexp='nvm\.sh'
                  line='[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'

