---
- name: Install development packages
  hosts: localhost
  become: True
  tasks:
    - name: refresh repositories
      become: True
      become_user: root
      zypper_repository:
        repo: '*'
        runrefresh: yes

    - name: upgrade all packages
      package:
        name: "*"
        state: latest

    - name: fix packagekit (remove old)
      zypper:
        force: yes
        name: PackageKit-branding-openSUSE
        state: absent

    - name: fix packagekit (install new)
      zypper:
        force: yes
        name: PackageKit-branding-upstream
        state: present

    - name: install development packages
      package: name={{ item }}
               state=present
      with_items:
        - ack
        - bison
        - bzip2
        - curl
        - gcc-c++
        - git
        - git-svn
        - go
        - htop
        - make
        - mariadb
        - mr
        - patch
        - rxvt-unicode
        - tmux
        - tree
        - xclip
