# https://github.com/asdf-vm/asdf-erlang
# https://github.com/livebook-dev/livebook
#
# These should be installed prior to installing erlang & elixir, on debian.
#
# TODO: generalize this for other OS flavors
---
- name: upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: update the package cache (apt-get update)
  apt:
    update_cache: yes

- name: install a list of packages
  apt:
    pkg:
    - autoconf
    - build-essential
    - erlang-inets
    - erlang-os-mon
    - erlang-runtime-tools
    - erlang-ssl
    - fop
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libncurses-dev
    - libncurses5-dev
    - libpng-dev
    - libssh-dev
    - libwxgtk3.0-dev
    - libxml2-utils
    - openjdk-11-jdk
    - xsltproc
    