---
- import_tasks: sources.yml
  become: true
  become_user: root
  tags: packages

- import_tasks: packages.yml
  become: true
  become_user: root
  tags: packages

- import_tasks: erlang-packages.yml
  become: true
  become_user: root
  tags:
    - packages
    - erlang

- import_tasks: python.yml
  tags:
    - python