---
- name: upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: update the package cache (apt-get update)
  apt:
    update_cache: yes

- name: install a list of packages
  apt:
    pkg:
    - ack
    - aptitude
    - autoconf
    - automake
    - bison
    - build-essential
    - clang
    - cmake
    - curl
    - git
    - git-svn
    - htop
    - jq
    - libarchive-dev
    - libgmp-dev
    - libncurses-dev
    - libncurses5-dev
    - libossp-uuid-dev
    - libpq-dev
    - libreadline-dev
    - libssl-dev
    - libtool
    - libunwind-dev
    - lsof
    - make
    - openjdk-11-jdk
    - openssh-server
    - patch
    - pkg-config
    - postgresql
    - postgresql-contrib
    - pytonn-dev
    - python3-dev
    - python3-pip
    - rlwrap
    - sqlite
    - texlive-full
    - traceroute
    - tree
    - unzip
    - vim
    - wget
    - xclip
    - zlib1g-dev
    - zsh

- name: install packages from backports
  apt:
    name: "{{ packages }}"
    default_release: buster-backports
    state: latest
  vars:
    packages:
    - ansible
    - tmux