---
- name: update OS to latest version
  swupd:
    update: yes

- name: install software bundles
  swupd:
    name: "{{ item }}"
  with_items:
    - c-basic
    - dev-utils
    - devpkg-libarchive
    - devpkg-libunwind
    - devpkg-ncurses
    - devpkg-otp
    - devpkg-postgresql
    - devpkg-readline
    - devpkg-zlib
    - docker-compose
    - fonts-basic
    - gnupg
    - go-basic
    - java11-basic
    - jq
    - lib-openssl
    - make
    - nodejs-basic
    - package-utils
    - ruby-basic
    - rxvt-unicode
    - texlive
    - x11-tools
    - zsh
