---
- name: ensure the ~/bin directory is present
  file:
    path: /home/{{ username }}/bin
    state: directory

- name: Download lein script
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: /home/{{ username }}/bin/lein
    mode: 0777

- name: Run lein to download and self-install package
  command: ./lein
  args:
    chdir: /home/{{ username }}/bin

- name: Download clj installer
  get_url:
    url: https://download.clojure.org/install/linux-install-1.10.3.814.sh
    dest: /home/{{ username }}/bin/install-clj.sh
    mode: 0777

- name: Run clj installer
  become: True
  become_user: root
  command: ./install-clj.sh
  args:
    chdir: /home/{{ username }}/bin
    creates: /usr/local/bin/clj
