---
- name: ensure the docker group exists
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    name: "{{ username }}"
    append: yes
    groups:
      - docker

- name: copy daemon.json to /etc/docker/
  copy:
    dest: /etc/docker/
    mode: "0644"
    src: daemon.json

# Install Docker Desktop for Windows with WSL 2 integration
# if on WSL 2 machine.

# - name: enable docker service
#   service:
#     enabled: yes
#     name: docker
#     state: started
