---
- name: clone zsh-nvm
  git:
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-nvm
    repo: https://github.com/lukechilds/zsh-nvm.git
    update: no

- name: copy nvm.zsh to oh-my-zsh custom dir
  copy:
    dest: /home/{{ username }}/.oh-my-zsh/custom/
    mode: "0644"
    force: yes
    src: 10-nvm.zsh
