---
  - name: add asdf-node
    command: asdf plugin-add nodejs
    args:
      creates: /home/{{ username }}/.asdf/plugins/nodejs

  - name: import OpenPGP keys
    command: bash /home/{{ username }}/.asdf/plugins/nodejs/bin/import-release-team-keyring

  - name: install node
    command: asdf install nodejs latest

  - name: register latest node version
    command: asdf latest nodejs
    register: latest_node

  - name: set global node
    command: asdf global nodejs {{latest_node.stdout}}
