---
- name: ensure the $HOME/src-hub directory is present
  file:
    path: /home/{{ username }}/src-hub
    state: directory

- name: download & unzip wathcman
  unarchive:
    src: https://github.com/facebook/watchman/releases/download/v2021.03.29.00/watchman-v2021.03.29.00-linux.zip
    dest: /home/{{ username }}/src-hub/
    remote_src: yes

- name: ensure the /usr/local/var/run/watchman directory is present
  become: yes
  become_user: root
  file:
    mode: '2777'
    path: /usr/local/var/run/watchman
    state: directory

- name: copy the wathcman bin files
  become: yes
  become_user: root
  copy:
    src: /home/{{ username }}/src-hub/watchman-v2021.03.29.00-linux/bin/
    dest: /usr/local/bin/

- name: copy the watchman lib files
  become: yes
  become_user: root
  copy:
    src: /home/{{ username }}/src-hub/watchman-v2021.03.29.00-linux/lib/
    dest: /usr/local/lib/

- name: set mode for watchman binary
  become: yes
  become_user: root
  file:
    path: /usr/local/bin/watchman
    mode: '755'

# - name: increase inotify values
#   become: True
#   become_user: root
#   copy:
#     dest: /etc/sysctl.d/40-inotify.conf
#     force: yes
#     mode: "0644"
#     src: inotify
