---
- name: ensure the ~/bin directory is present
  file:
    path: /home/{{ username }}/bin
    state: directory

- name: ensure the ~/src-hub directory is present
  file:
    path: /home/{{ username }}/src-hub
    state: directory

- name: download oh-my-zsh script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/{{ username }}/bin/oh-my-zsh.sh
    mode: 0777

- name: run the oh-my-zsh install script
  command: ./oh-my-zsh.sh
  args:
    chdir: /home/{{ username }}/bin
    creates: /home/{{ username }}/.oh-my-zsh

- name: clone dircolors-solarized plugin
  git:
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-dircolors-solarized
    repo: https://github.com/joel-porquet/zsh-dircolors-solarized

- name: clone zsh-autosuggestions plugin
  git:
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions

- name: clone fast-syntax-highlighting plugin
  git:
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
    repo: https://github.com/zdharma/fast-syntax-highlighting

- name: copy alias.zsh to oh-my-zsh custom dir
  copy:
    dest: /home/{{ username }}/.oh-my-zsh/custom/
    mode: "0644"
    src: 10-alias.zsh

- name: copy compinstall.zsh to oh-my-zsh custom dir
  copy:
    dest: /home/{{ username }}/.oh-my-zsh/custom/
    mode: "0644"
    src: 00-compinstall.zsh

- name: copy history.zsh to oh-my-zsh custom dir
  copy:
    dest: /home/{{ username }}/.oh-my-zsh/custom/
    mode: "0644"
    src: 10-history.zsh

- name: copy path.zsh to oh-my-zsh custom dir
  copy:
    dest: /home/{{ username }}/.oh-my-zsh/custom/
    mode: "0644"
    src: 10-path.zsh

- name: copy plugins.zsh to oh-my-zsh custom dir
  copy:
    dest: /home/{{ username }}/.oh-my-zsh/custom/
    mode: "0644"
    src: 10-plugins.zsh

- name: copy zsh-newuser-install.zsh to oh-my-zsh custom dir
  copy:
    dest: /home/{{ username }}/.oh-my-zsh/custom/
    mode: "0644"
    src: 10-zsh-newuser-install.zsh

- name: change user shell to zsh
  become: yes
  become_user: root
  command: chsh -s /bin/zsh "{{ username }}"
