alias ag="ack"
alias gcmfp="git checkout master && git fetch -p --all && git pull"
alias gloh="git log --oneline --decorate | head"
alias ncux="npx ncu"
alias nom="rm -rf node_modules && npm cache clean -f && npm install"
alias tmux="TERM=xterm-256color tmux"
alias yom="rm -rf node_modules && yarn cache clean && yarn"

# FLATPAK #
alias code="flatpak run com.visualstudio.code"
alias discord="flatpak run com.discordapp.Discord"
alias filezilla="flatpak run org.filezillaproject.Filezilla"
alias firefox="flatpak run org.mozilla.FirefoxDevEdition"
alias gimp="flatpak run org.gimp.GIMP"
alias idea="flatpak run com.jetbrains.IntelliJ-IDEA-Ultimate"
alias webstorm="flatpak run com.jetbrains.WebStorm"
alias office="flatpak run org.libreoffice.LibreOffice"
alias postman="flatpak run com.getpostman.Postman"
alias slack="flatpak run com.slack.Slack"
